name: SkyblockCore
version: 0.1.0
author: Biswajit
main: Biswajit\Core\Skyblock
api: 5.30.0
description: A Skyblock plugin for PocketMine

permissions:
  weather.command.bt:
    default: op
  island.cmd:
    default: true
  player.hub.cmd:
    default: true
  staff.mw.cmd:
    default: op
  staff.economy.cmd:
    default: op
  player.bank.cmd:
    default: true
  player.topmoney.cmd:
    default: true
  player.topbank.cmd:
    default: true
