 # ██████╗░██╗░██████╗░██╗░░░░░░░██╗░█████╗░░░░░░██╗██╗████████╗
 # ██╔══██╗██║██╔════╝░██║░░██╗░░██║██╔══██╗░░░░░██║██║╚══██╔══╝
 # ██████╦╝██║╚█████╗░░╚██╗████╗██╔╝███████║░░░░░██║██║░░░██║░░░
 # ██╔══██╗██║░╚═══██╗░░████╔═████║░██╔══██║██╗░░██║██║░░░██║░░░
 # ██████╦╝██║██████╔╝░░╚██╔╝░╚██╔╝░██║░░██║╚█████╔╝██║░░░██║░░░
 # ╚═════╝░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝░╚════╝░╚═╝░░░╚═╝░░░

# License: This configuration file is released under public domain.
# You are free to use, modify, and distribute this configuration as you wish.
# No attribution required.

HUB: Hub

PREFIX: §l§6SKYBLOCK§r §l§a»§r §e
SERVER-MOTD: §eYour Motd

SERVER-NAME: §eYour Server
VOTE-WEBSITE: §ehttps:://yourvotelink.com
DISCORD-LINK: §ehttps:://discord.gg/yourdiscord

database:
  # The database type. "sqlite" and "mysql" are supported.
  type: sqlite

  # Edit these settings only if you choose "sqlite".
  sqlite:
    # The file name of the database in the plugin data folder.
    # You can also put an absolute path here.
    file: skyblock.sql

  # Edit these settings only if you choose "mysql".
  mysql:
    host: 127.0.0.1
    # Avoid using the "root" user for security reasons.
    username: root
    password: ""
    schema: skyblock
  # The maximum number of simultaneous SQL queries
  # Recommended: 1 for sqlite, 2 for MySQL. You may want to further increase this value if your MySQL connection is very slow.
  worker-limit: 1
