name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, intl, zip

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run tests
      run: composer test
      continue-on-error: true  # Since there might not be tests

    - name: Check PHP syntax
      run: find src -name "*.php" -exec php -l {} \;

    - name: Build PHAR (if DevTools available)
      run: |
        if [ -f "plugin.yml" ]; then
          echo "Plugin detected, PHAR build would go here if DevTools is set up"
        fi
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: skyblock-plugin
        path: |
          src/
          plugin.yml
          composer.json
          composer.lock
          resources/
